server:
  port: ${PORT:9999}
  
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: *
        
info:
  author: Rafaela Lopes Meira S S
  country: Brazil 
  message: Application Global
