server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      profiles:
        active: dev
      server:
        git:
          uri: https://github.com/meirafa/configCloudDh

eureka:
  instance:
    hostname: localhost
