server:
  port: 8080
spring:  
  cloud:
    gateway:
      routes:
        - id: jogosRoute
          uri: lb://JOGOS
          predicates:
           - Path=/jogos/**
        - id: bibliotecaRoute
          uri: lb://BIBLIOTECA
          predicates:
           - Path=/biblioteca/**
        - id: musicaRoute
          uri: lb://MUSICA
          predicates:
           - Path=/musica/**
        - id: playlistRoute
          uri: lb://PLAYLIST
          predicates:
           - Path=/playlist/**
        - id: catalogRoute
          uri: lb://CATALOG
          predicates:
           - Path=/catalog/**
        - id: movieRoute
          uri: lb://MOVIE
          predicates:
           - Path=/movies/**
        - id: serieRoute
          uri: lb://SERIE
          predicates:
           - Path=/series/**